<?php

namespace ContainerR6Dxx7V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JKF9tQ8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JKF9tQ8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JKF9tQ8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'validatorInterface' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'entityManager' => '?',
            'validatorInterface' => '?',
        ]);
    }
}
