<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjCd6c5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjCd6c5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFjCd6c5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFjCd6c5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFjCd6c5\App_KernelDevDebugContainer([
    'container.build_hash' => 'FjCd6c5',
    'container.build_id' => '629b3e15',
    'container.build_time' => 1646746470,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjCd6c5');
