<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'api_avis_delete_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\AvisController::deleteAvis'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/avis']], [], [], []],
    'api_avis_list_avis' => [[], ['_controller' => 'App\\Controller\\Api\\AvisController::listAvis'], [], [['text', '/api/avis']], [], [], []],
    'api_avis_edit_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\AvisController::editAvis'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/avis']], [], [], []],
    'api_professeurs_list' => [[], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::list'], [], [['text', '/api/professeurs']], [], [], []],
    'api_professeurs_name' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], [], []],
    'api_professeurs_list_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::listAvis'], [], [['text', '/avis'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], [], []],
    'api_professeurs_create_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::createAvis'], [], [['text', '/avis'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], [], []],
    'professeurs_list' => [[], ['_controller' => 'App\\Controller\\ProfesseurController::list'], [], [['text', '/professeurs']], [], [], []],
    'professeurs_create' => [[], ['_controller' => 'App\\Controller\\ProfesseurController::create'], [], [['text', '/professeurs/create']], [], [], []],
    'professeurs_update' => [['id'], ['_controller' => 'App\\Controller\\ProfesseurController::update'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/professeurs']], [], [], []],
    'professeurs_delete' => [['id'], ['_controller' => 'App\\Controller\\ProfesseurController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/professeurs']], [], [], []],
];
